# fly.toml app configuration file generated for fly-next-test on 2024-01-14T22:07:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-next-test"
primary_region = "waw"
memory_mb = 256

[build]

[http_service]
internal_port = 3000
force_https = true
processes = ["app"]
swap_size_mb = 512

[[vm]]
cpu_kind = "shared"
cpus = 1
